# Generated by Django 4.0.3 on 2022-04-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_myuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(default=0, max_length=12, verbose_name='Phone No'),
        ),
    ]
