# Generated by Django 4.0.3 on 2022-04-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Patient', 'PATIENT'), ('Doctor', 'DOCTOR')], default='Patient', max_length=20),
        ),
    ]
