# Generated by Django 4.0.3 on 2022-04-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0008_appointmentmade'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='doctor_name',
            field=models.CharField(default='Not_Specified', max_length=100),
            preserve_default=False,
        ),
    ]
