# Generated by Django 4.0.3 on 2022-04-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_appointments_doctor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='doctor_name',
            new_name='patient_name',
        ),
    ]
